/************************************************************\
 **  Copyright (c) 2011-2017 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/Works/NGV/99-8b/vhdl/ngv-main/al_ip/pll.v
 ** Date	:	2018 10 16
 ** TD version	:	4.1.389
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             24.000Mhz
//	Clock multiplication factor: 7
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 168.000MHZ	| 0  DEG     
//		C1        	| 1176.000MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module pll(refclk,
		clk0_out,
		clk1_out);

	input refclk;
	output clk0_out;
	output clk1_out;

	wire clk0_buf;

	AL_LOGIC_BUFG bufg_feedback( .i(clk0_buf), .o(clk0_out) );

	AL_PHY_PLL #(.FIN("24.000"),
		.FEEDBK_PATH("CLKC0_EXT"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("DISABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("ENABLE"),
		.GEN_BASIC_CLOCK("ENABLE"),
		.GMC_GAIN("6"),
		.ICP_CURRENT(3),
		.KVCO("6"),
		.LPF_CAPACITOR("3"),
		.LPF_RESISTOR(2),
		.REFCLK_DIV(1),
		.FBCLK_DIV(7),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(7),
		.CLKC0_CPHASE(7),
		.CLKC0_FPHASE("0"),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(1),
		.CLKC1_CPHASE(1),
		.CLKC1_FPHASE("0")	)
	pll_inst (.refclk(refclk),
		.pllreset(1'b0),
		.stdby(1'b0),
		.ext_lock(open),
		.scanclk(1'b0),
		.phaseupdown(1'b0),
		.phasestep(1'b0),
		.phcntsel(3'b000),
		.phasedone(open),
		.fbclk(clk0_out),
		.clkc({open, open, open, clk1_out, clk0_buf}));

endmodule
