/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/Works/NGV/99-8b/vhdl/ngv-main/al_ip/sdram.v
 ** Date	:	2018 11 10
 ** TD version	:	4.2.511
\************************************************************/

`timescale 1ns / 1ps

module sdram ( clk, ras_n, cas_n, we_n, addr, ba, dq, dm, dm0, cke );
	input  		clk;
	input  		ras_n;
	input  		cas_n;
	input  		we_n;
	input  		[10:0] addr;
	input  		[1:0] ba;
	inout  		[31:0] dq;
	input  		dm;
	input  		dm0;
	input  		cke;

		AL_PHY_SDRAM_2M_32 sdram(
		.clk(clk),
		.ras_n(ras_n),
		.cas_n(cas_n),
		.we_n(we_n),
		.addr(addr),
		.ba(ba),
		.dq(dq),
		.dm(dm),
		.dm0(dm0),
		.cke(cke));

endmodule