# ## Log	:	This file is generated by Anlogic Timing Wizard.
# ## File	:	E:/Works/NGV/99-8b/vhdl/ngv-main/ngv-main.sdc
# ## Date	:	13 10 2018

#Created Clock
create_clock -name stm_clk -period 24 -waveform {0 12} [get_ports {clk}]

